[versions]
agp = "8.13.2"
#noinspection UnusedVersionCatalogEntry
android-compileSdk = "36"
#noinspection UnusedVersionCatalogEntry
android-minSdk = "28"
#noinspection UnusedVersionCatalogEntry
android-targetSdk = "36"

android-cacheFixPlugin = "3.0.3"
androidx-activityCompose = "1.12.2"
androidx-browser = "1.9.0"
androidx-core-splashscreen = "1.2.0"
androidx-datastore = "1.2.0"
androidx-webkit = "1.15.0"
androidx-work = "2.11.0"
buildConfig = "0.17.1"
circuit = "0.32.0"
coil = "3.3.0"
compose-plugin = "1.10.0"
compose-material3Version = "1.9.0"
compose-materialIconsExtended = "1.7.3"
detekt = "1.23.8"
doctor = "0.12.1"
haze = "1.7.1"
kotlin = "2.3.0"
kotlin-atomic = "0.31.0"
kotlin-coroutines = "1.10.2"
kotlinx-collections = "0.4.0"
kotlinx-datetime = "0.7.1"
kotlinx-serialization = "1.10.0"
ktor = "3.4.0"
metro = "0.10.0"
napier = "2.7.1"
rssparser = "6.1.2"
shimmer = "1.3.3"
stability-analyzer = "0.6.6"
sqldelight = "2.2.1"
stately = "2.1.0"
turbine = "1.2.1"

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidCacheFixPlugin = { id = "org.gradle.android.cache-fix", version.ref = "android-cacheFixPlugin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
buildConfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildConfig" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
doctor = { id = "com.osacky.doctor", version.ref = "doctor" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
kotlinAtomic = { id = "org.jetbrains.kotlinx.atomicfu", version.ref = "kotlin-atomic" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinParcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
metro = { id = "dev.zacsweers.metro", version.ref = "metro" }
peek-android-application = { id = "com.illiarb.peek.android.application" }
peek-android-library = { id = "com.illiarb.peek.android.library" }
peek-compose = { id = "com.illiarb.peek.compose" }
peek-multiplatform = { id = "com.illiarb.peek.kotlin.multiplatform" }
stabilityAnalyzer = { id = "com.github.skydoves.compose.stability.analyzer", version.ref = "stability-analyzer" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidx-browser" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-core-splashscreen" }
androidx-datastore = { module = "androidx.datastore:datastore-preferences-core", version.ref = "androidx-datastore" }
androidx-webkit = { module = "androidx.webkit:webkit", version.ref = "androidx-webkit" }
androidx-work = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }

# All used inside convention plugin
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose-plugin" }
compose-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose-plugin" }
compose-uiTooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose-plugin" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose-plugin" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose-plugin" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose-plugin" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose-material3Version" }
compose-material3IconsExtended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "compose-materialIconsExtended" }

circuit-core = { module = "com.slack.circuit:circuit-foundation", version.ref = "circuit" }
circuit-overlay = { module = "com.slack.circuit:circuit-overlay", version.ref = "circuit" }
circuit-x-android = { module = "com.slack.circuit:circuitx-android", version.ref = "circuit" }
circuit-x-gestureNavigation = { module = "com.slack.circuit:circuitx-gesture-navigation", version.ref = "circuit" }
circuit-x-overlay = { module = "com.slack.circuit:circuitx-overlays", version.ref = "circuit" }

coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }

gradlePlugin-android = { module = "com.android.tools.build:gradle", version.ref = "agp" }
gradlePlugin-compose = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose-plugin" }
gradlePlugin-composeCompiler = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
gradlePlugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradlePlugin-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }

haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }
haze-materials = { module = "dev.chrisbanes.haze:haze-materials", version.ref = "haze" }

kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlin-coroutines" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-coroutines" }
kotlinx-collections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

sqldelight-android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-coroutines = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
sqldelight-native = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight" }
sqldelight-primitive = { module = "app.cash.sqldelight:primitive-adapters", version.ref = "sqldelight" }

# Misc
napier = { module = "io.github.aakira:napier", version.ref = "napier" }
rssparser = { module = "com.prof18.rssparser:rssparser", version.ref = "rssparser" }
shimmer = { module = "com.valentinilk.shimmer:compose-shimmer", version.ref = "shimmer" }
stately-collections = { module = "co.touchlab:stately-concurrent-collections", version.ref = "stately" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

#noinspection UnusedVersionCatalogEntry
tools-desugarJdkLibs = "com.android.tools:desugar_jdk_libs:2.1.5"
