name: Server

on:
  workflow_dispatch:  # Add this line to enable manual triggering
  push:
    paths:
      - 'server/**'
      - '.github/workflows/server.yml'
    branches:
      - master

env:
  SQLX_VERSION: 0.8.6
  SQLX_FEATURES: "rustls,postgres"
  APP_USER: app
  APP_USER_PWD: secret
  APP_DB_NAME: peek
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./server
  #   services:
  #     postgres:
  #       image: postgres:14
  #       env:
  #         POSTGRES_USER: postgres
  #         POSTGRES_PASSWORD: password
  #         POSTGRES_DB: postgres
  #       ports:
  #         - 5432:5432
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v4

  #     - name: Install the Rust toolchain
  #       uses: actions-rust-lang/setup-rust-toolchain@v1

  #     - name: Install sqlx-cli
  #       run:
  #         cargo install sqlx-cli
  #         --version=${{ env.SQLX_VERSION }}
  #         --features ${{ env.SQLX_FEATURES }}
  #         --no-default-features
  #         --locked

  #     - name: Create database user
  #       run: |
  #         sudo apt-get install postgresql-client

  #         CREATE_QUERY="CREATE USER ${APP_USER} WITH PASSWORD '${APP_USER_PWD}';"
  #         PGPASSWORD="password" psql -U "postgres" -h "localhost" -c "${CREATE_QUERY}"

  #         GRANT_QUERY="ALTER USER ${APP_USER} CREATEDB;"
  #         PGPASSWORD="password" psql -U "postgres" -h "localhost" -c "${GRANT_QUERY}"

  #     - name: Migrate database
  #       run: |
  #         SKIP_DOCKER=true ./scripts/init_db.sh

  #     - name: Run tests
  #       run: cargo test

  #     - name: Check that queries are fresh
  #       run: cargo sqlx prepare --workspace --check -- --all-targets

  deploy:
    name: Deploy
    #needs: test
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl apps list
      - run: flyctl deploy ./server --remote-only --app peek-dzdqh
